# Generated by Django 2.0.1 on 2018-05-17 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patashala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter school name', max_length=200, verbose_name='Patashala Name')),
                ('address', models.CharField(help_text='Enter door number, street name', max_length=200, verbose_name='Full Address')),
                ('city', models.CharField(help_text='Enter locality', max_length=50, verbose_name='City/Town')),
                ('state', models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CT', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UT', 'Uttarakhand'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal'), ('AN', 'Andaman and Nicobar Islands'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('LD', 'Lakshadweep'), ('PY', 'Puducherry')], help_text='Chose State', max_length=50, verbose_name='State')),
                ('pincode', models.PositiveSmallIntegerField(help_text='Enter Pin Code', verbose_name='Pin Code')),
                ('phone1', models.CharField(help_text='Enter Primary Contact Number of Patashala', max_length=20, verbose_name='Patashala Contact Number1')),
                ('phone2', models.CharField(blank=True, help_text='Enter Secondary Contact Number of Patashala', max_length=20, null=True, verbose_name='Patashala Contact Number2')),
                ('number_of_students', models.PositiveSmallIntegerField(blank=True, help_text='Enter number of students in Patashala', null=True, verbose_name='Number of Students')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dor', models.DateField(blank=True, help_text='Enter in dd/mm/yyyy format', null=True, verbose_name='Date of Registration')),
                ('mode', models.CharField(choices=[('A', 'Already Registered'), ('O', 'On Spot Registration')], help_text='Choose an option', max_length=30, verbose_name='Registration Mode')),
                ('comments', models.CharField(max_length=50)),
                ('patashala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPVC10.Patashala')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter students name', max_length=200, verbose_name='Name')),
                ('parent_name', models.CharField(help_text='Enter Students Fathers name', max_length=200, verbose_name='Fathers Name')),
                ('dob', models.DateField(blank=True, help_text='Enter in dd/mm/yyyy format', null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media')),
                ('patashala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPVC10.Patashala')),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPVC10.Student'),
        ),
    ]
